<a href="https://colab.research.google.com/github/Ricardomanuel1/Maestria_Ciencia_de_Datos/blob/main/Actividad_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Elaborar una función en python que simule los estados de una cadena de Markov teniendo como datos la matriz P y la distribución inicial p0 y con estados S={1,2,...n}

In [400]:
import numpy as np
import random
import matplotlib.pyplot as plt

Creamos las matrices P y p0 con distribución uniforme, ambas de tamaño n

In [401]:
import numpy as np
np.random.seed(101)
def matriz_P(n):
    matriz = np.random.uniform(0, 1,size=(n, n))  # Genera matriz aleatoria
    matriz =matriz/matriz.sum(axis=1, keepdims=True)
    return matriz
np.random.seed(101)
def matriz_p0(n):
    fila = np.random.uniform(0, 1, size=(1, n))  # Genera una fila aleatoria con distribución uniforme
    fila =fila/np.sum(fila)
    return fila

n = 4  # Tamaño de la matriz P y de la matriz p0

P = matriz_P(n)
p0= matriz_p0(n)

In [402]:
print(P)#matriz de tamaño nxn

[[0.40122278 0.44338777 0.02212343 0.13326603]
 [0.25196293 0.30660756 0.11286547 0.32856404]
 [0.39692323 0.10448593 0.3048821  0.19370874]
 [0.08400212 0.36280908 0.4458825  0.1073063 ]]


In [403]:
print(p0)

[[0.04937623 0.35663514 0.43075986 0.16322878]]


Efectuamos la multiplicación de las matrices p0*P, el resultado multiplicamos nuevamente por P y asi hata obtener pn

In [404]:
p1=p0@P
p2=p1@P
p3=p2@P
p4=p3@P
#p5=p4@P

Creamos un función que sume los indices con la finalidad de obtener los intervalos, teniendo en cuenta que el último valor sera 1

In [405]:
def intervalos(matrix):
  lista=[]
  suma=0
  for i in range(len(matrix)):#0
    for j in range(len(matrix[0])):#0,1,2
      suma=suma+matrix[i][j]
      lista.append(suma)
  return lista

In [406]:
list_matrix=[p0,p1,p2,p3,p4,p5]

In [407]:
for i in range(n+1):
  print(f'Intervalos p{i}',intervalos(list_matrix[i]))

Intervalos p0 [0.04937622609859187, 0.40601136331467996, 0.8367712202253136, 1.0]
Intervalos p1 [0.2943598596808149, 0.5298289302618012, 0.7752849193963331, 1.0]
Intervalos p2 [0.29373708559597056, 0.6036246111837819, 0.8117448468365791, 1.0]
Intervalos p3 [0.29435576757394766, 0.6096553696328506, 0.7985212549355034, 1.0]
Intervalos p4 [0.28943595038538406, 0.6094550824380738, 0.79897135317823, 1.0000000000000002]


Creamos los números aleatorios (n+1), estos números serán ubicados en los intervalos 1,2...n y según en que intervalo se encuentre tendremos el estado

In [408]:
def aleatorios(n):
    aleatorios = []
    for k in range(n):
      numero = random.random()
      aleatorios.append(numero)
    return aleatorios

Con el primer número aleatorio creado ubicamos en que posicion se encuentra en la matriz p0, con el segundo número aleatorio ubicamos en la matriz p1 y asi sucesivamente hasta pn

In [409]:
def estado(aleatorio,intervalo):

  for i in range(len(intervalo)):
    list10=[]
    if aleatorio<intervalo[i]:
      list10.append(1)
    elif aleatorio<intervalo[i+1]:
      list10.append(2)
    elif aleatorio<intervalo[i+2]:
      list10.append(3)
    elif aleatorio<intervalo[i+3]:
      list10.append(4)
    elif aleatorio<intervalo[i+4]:
      list10.append(5)
    elif aleatorio<intervalo[i+5]:
      list10.append(6)
    elif aleatorio<intervalo[i+6]:
      list10.append(7)
    elif aleatorio<intervalo[i+7]:
      list10.append(8)
    elif aleatorio<intervalo[i+8]:
      list10.append(9)
    elif aleatorio<intervalo[i+9]:
      list10.append(10)
    return list10

Realizamos nsim simulaciones

In [417]:
nsim=1
lista_estado=[]

for i in range (nsim):#0,1,2
  random_num=aleatorios(n+1)
  print('Números aleatorios:',random_num)
  for i in range(n+1):
    e=estado(random_num[i],intervalos(list_matrix[i]))
    lista_estado.append(e)
print('Estados:',lista_estado)

Números aleatorios: [0.7501935059211469, 0.7472447204754505, 0.2858919722942357, 0.2944468349037107, 0.26023908106818483]
Estados: [[3], [3], [1], [2], [1]]


Realizamos la comprobación y efectivamente es conforme los estado de acuerdo a que intervalo se encuentra el numero aleatorio

In [413]:
for i in range(n+1):
  s=intervalos(list_matrix[i])
  print(f'p{i}:',s)

p0: [0.04937622609859187, 0.40601136331467996, 0.8367712202253136, 1.0]
p1: [0.2943598596808149, 0.5298289302618012, 0.7752849193963331, 1.0]
p2: [0.29373708559597056, 0.6036246111837819, 0.8117448468365791, 1.0]
p3: [0.29435576757394766, 0.6096553696328506, 0.7985212549355034, 1.0]
p4: [0.28943595038538406, 0.6094550824380738, 0.79897135317823, 1.0000000000000002]
