<a href="https://colab.research.google.com/github/Ricardomanuel1/Maestria_Ciencia_de_Datos/blob/main/Actividad_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Elaborar una función en python que simule los estados de una cadena de Markov teniendo como datos la matriz P y la distribución inicial p0 y con estados S={1,2,...n}

In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt

In [108]:
import numpy as np
np.random.seed(101)
def matriz_P(n):
    matriz = np.random.uniform(0, 1,size=(n, n))  # Genera matriz aleatoria
    matriz =matriz/matriz.sum(axis=1, keepdims=True)
    return matriz
np.random.seed(101)
def matriz_p0(n):
    fila = np.random.uniform(0, 1, size=(1, n))  # Genera una fila aleatoria con distribución uniforme
    fila =fila/np.sum(fila)
    return fila

n = 3  # Tamaño de la matriz P y de la matriz p0

P = matriz_P(n)
p0= matriz_p0(n)

In [109]:
print(P)

[[0.46291341 0.51156154 0.02552505]
 [0.10145035 0.40532253 0.49322711]
 [0.15970164 0.46490938 0.37538898]]


In [110]:
print(p0)

[[0.17325478 0.50554442 0.3212008 ]]


In [111]:
p1=p0@P
p2=p1@P
p3=p2@P

In [151]:
numero1_aleatorio = random.random()
numero1_aleatorio

0.7656609117120138

In [134]:
for i in range(len(p0)):#0
    for j in range(len(p0[0])):#
      print(p0[i][j])


0.17325477898249295
0.5055444219345895
0.3212007990829175


In [152]:
intervalo_1=p0[0][0]
intervalo_1

0.17325477898249295

In [153]:
intervalo_2=p0[0][0]+p0[0][1]#>intervalo_1 y < intervalo 2
intervalo_2

0.6787992009170825

In [155]:
intervalos=[]

if numero1_aleatorio <intervalo_1:
  intervalos.append(1)
elif   numero1_aleatorio <intervalo_2:
  intervalos.append(2)
else:
  intervalos.append(3)

In [156]:
print(intervalos)

[3]


In [113]:
for i,j in p0:
  print(0,0)


ValueError: too many values to unpack (expected 2)

In [132]:
def separar_en_intervalos(matriz):
    intervalos = []

    for valor in matriz.flatten():  # Aplanamos la matriz y recorremos los valores
        if valor < 0.33:
            intervalos.append("Intervalo 1: Menor que 0.33")
        elif valor < 0.66:
            intervalos.append("Intervalo 2: Entre 0.33 y 0.66")
        else:
            intervalos.append("Intervalo 3: Mayor o igual que 0.66")

    return intervalos

# Matriz de 3x1
matriz = np.random.rand(3, 1)
print(matriz)
separar_en_intervalos(matriz)

[[0.72899276]
 [0.27623883]
 [0.68530633]]


['Intervalo 3: Mayor o igual que 0.66',
 'Intervalo 1: Menor que 0.33',
 'Intervalo 3: Mayor o igual que 0.66']