<a href="https://colab.research.google.com/github/Ricardomanuel1/Maestria_Ciencia_de_Datos/blob/main/Actividad_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Elaborar una función en python que simule los estados de una cadena de Markov teniendo como datos la matriz P y la distribución inicial p0 y con estados S={1,2,...n}

In [356]:
import numpy as np
import random
import matplotlib.pyplot as plt

In [357]:
import numpy as np
np.random.seed(101)
def matriz_P(n):
    matriz = np.random.uniform(0, 1,size=(n, n))  # Genera matriz aleatoria
    matriz =matriz/matriz.sum(axis=1, keepdims=True)
    return matriz
np.random.seed(101)
def matriz_p0(n):
    fila = np.random.uniform(0, 1, size=(1, n))  # Genera una fila aleatoria con distribución uniforme
    fila =fila/np.sum(fila)
    return fila

n = 3  # Tamaño de la matriz P y de la matriz p0

P = matriz_P(n)
p0= matriz_p0(n)

In [358]:
print(P)

[[0.46291341 0.51156154 0.02552505]
 [0.10145035 0.40532253 0.49322711]
 [0.15970164 0.46490938 0.37538898]]


In [359]:
print(p0)

[[0.17325478 0.50554442 0.3212008 ]]


In [360]:
p1=p0@P
p2=p1@P
p3=p2@P

In [361]:
def intervalos(matrix):
  lista=[]
  suma=0
  for i in range(len(matrix)):#0
    for j in range(len(matrix[0])):#0,1,2
      suma=suma+matrix[i][j]
      lista.append(suma)
  return lista

In [452]:
print(intervalos(p0))
print(intervalos(p1))
print(intervalos(p2))
print(intervalos(p3))

[0.17325477898249295, 0.6787992009170825, 1.0]
[0.18278591471625064, 0.6256542048282535, 0.9999999999999999]
[0.18932683250678567, 0.6363744436091698, 0.9999999999999998]
[0.19106666494032654, 0.6381703914696727, 0.9999999999999998]


In [481]:
def aleatorios(n):
    aleatorios = []
    for k in range(n):
      numero = random.random()
      aleatorios.append(numero)
    return aleatorios
random_num=aleatorios(n+1)
random_num

[0.41729146477740553,
 0.40332655945724083,
 0.8286808335302308,
 0.16636274530902162]

In [478]:
def estado(aleatorio,intervalo):

  for i in range(len(intervalo)):
    list10=[]
    if aleatorio<intervalo[i]:
      list10.append(1)
    elif aleatorio<intervalo[i+1]:
      list10.append(2)
    else:
      list10.append(3)
    return list10

In [479]:
list_estado=[]

In [482]:
e0=estado(random_num[0],intervalos(p0))
list_estado.append(e0)
e1=estado(random_num[1],intervalos(p1))
list_estado.append(e1)
e2=estado(random_num[2],intervalos(p2))
list_estado.append(e2)
e3=estado(random_num[3],intervalos(p3))
list_estado.append(e3)
print(list_estado)

[[2], [3], [3], [1], [2], [2], [3], [1]]
