<a href="https://colab.research.google.com/github/Ricardomanuel1/Maestria_Ciencia_de_Datos/blob/main/Actividad_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Elaborar una función en python que simule los estados de una cadena de Markov teniendo como datos la matriz P y la distribución inicial p0 y con estados S={1,2,...n}

In [14]:
import numpy as np
import random
import matplotlib.pyplot as plt

Creamos las matrices P y p0 con distribución uniforme, ambas de tamaño n

In [35]:
import numpy as np
np.random.seed(101)
def matriz_P(n):
    matriz = np.random.uniform(0, 1,size=(n, n))  # Genera matriz aleatoria
    matriz =matriz/matriz.sum(axis=1, keepdims=True)
    return matriz
np.random.seed(101)
def matriz_p0(n):
    fila = np.random.uniform(0, 1, size=(1, n))  # Genera una fila aleatoria con distribución uniforme
    fila =fila/np.sum(fila)
    return fila

n = 3  # Tamaño de la matriz P y de la matriz p0

P = matriz_P(n)
p0= matriz_p0(n)

In [36]:
print(P)#matriz de tamaño nxn

[[0.46291341 0.51156154 0.02552505]
 [0.10145035 0.40532253 0.49322711]
 [0.15970164 0.46490938 0.37538898]]


In [37]:
print(p0)

[[0.17325478 0.50554442 0.3212008 ]]


Efectuamos la multiplicación de las matrices p0*P, el resultado multiplicamos nuevamente por P y asi hata obtener pn

In [38]:
p1=p0@P
p2=p1@P
p3=p2@P
p4=p3@P
#p5=p4@P

Creamos un función que sume los indices con la finalidad de obtener los intervalos, teniendo en cuenta que el último valor sera 1

In [39]:
def intervalos(matrix):
  lista=[]
  suma=0
  for i in range(len(matrix)):#0
    for j in range(len(matrix[0])):#0,1,2
      suma=suma+matrix[i][j]
      lista.append(suma)
  return lista

In [40]:
list_matrix=[p0,p1,p2,p3,p4]

In [41]:
for i in range(n+2):
  print(f'Intervalos p{i}',intervalos(list_matrix[i]))

Intervalos p0 [0.17325477898249295, 0.6787992009170825, 1.0]
Intervalos p1 [0.18278591471625064, 0.6256542048282535, 0.9999999999999999]
Intervalos p2 [0.18932683250678567, 0.6363744436091698, 0.9999999999999998]
Intervalos p3 [0.19106666494032654, 0.6381703914696727, 0.9999999999999998]
Intervalos p4 [0.19159093381464337, 0.6387724835520283, 0.9999999999999998]


Creamos los números aleatorios (n+1), estos números serán ubicados en los intervalos 1,2...n y según en que intervalo se encuentre tendremos el estado

In [51]:
def aleatorios(n):
    aleatorios = []
    for k in range(n+2):
      numero = random.random()
      aleatorios.append(numero)
    return aleatorios
aleatorios(3)

[0.13099120431083444,
 0.14048918878487127,
 0.0459052269798903,
 0.6640139468565073,
 0.04727469879481916]

Con el primer número aleatorio creado ubicamos en que posicion se encuentra en la matriz p0, con el segundo número aleatorio ubicamos en la matriz p1 y asi sucesivamente hasta pn

In [60]:
def estado(aleatorio,intervalo):

  for i in range(len(intervalo)):
    list10=[]
    if aleatorio<intervalo[i]:
      list10.append(1)
    elif aleatorio<intervalo[i+1]:
      list10.append(2)
    elif aleatorio<intervalo[i+2]:
      list10.append(3)
    elif aleatorio<intervalo[i+3]:
      list10.append(4)
    elif aleatorio<intervalo[i+4]:
      list10.append(5)
    elif aleatorio<intervalo[i+5]:
      list10.append(6)
    elif aleatorio<intervalo[i+6]:
      list10.append(7)
    elif aleatorio<intervalo[i+7]:
      list10.append(8)
    elif aleatorio<intervalo[i+8]:
      list10.append(9)
    elif aleatorio<intervalo[i+9]:
      list10.append(10)
    return list10

Realizamos nsim simulaciones

In [62]:
nsim=1
lista_estado=[]

for i in range (nsim):#0,1,2
  random_num=aleatorios(n)
  print('Números aleatorios:',random_num)
  for i in range(n+2):
    e=estado(random_num[i],intervalos(list_matrix[i]))
    lista_estado.append(e)
print('Estados:',lista_estado)

Números aleatorios: [0.3754021803922146, 0.8253259790661942, 0.8367517517800563, 0.5050603686002682, 0.10657087254655428]
Estados: [[2], [3], [3], [2], [1]]


Realizamos la comprobación y efectivamente es conforme los estado de acuerdo a que intervalo se encuentra el numero aleatorio

In [57]:
for i in range(n+2):
  s=intervalos(list_matrix[i])
  print(f'p{i}:',s)

p0: [0.17325477898249295, 0.6787992009170825, 1.0]
p1: [0.18278591471625064, 0.6256542048282535, 0.9999999999999999]
p2: [0.18932683250678567, 0.6363744436091698, 0.9999999999999998]
p3: [0.19106666494032654, 0.6381703914696727, 0.9999999999999998]
p4: [0.19159093381464337, 0.6387724835520283, 0.9999999999999998]
