<a href="https://colab.research.google.com/github/Ricardomanuel1/Maestria_Ciencia_de_Datos/blob/main/2.%20Numpy/Numpy_clase_UCSP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy
Es un paquete de python que significa "Numerical Python", es la librería principal para informática científica, proporciona potentes estructuras de datos.
Numpy es una biblioteca para el lenguaje de programación python que da soporte para crear vectores y matrices multidimensionales.

Una matriz es una lista de listas.


In [1]:
#pip install numpy cuando se trabajo en modo offline
import numpy as np
import random
import matplotlib.pyplot as plt

Diferencias entre una matriz y una lista

In [ ]:
x1=[2.0,4.6,9.3,1.2]
print(type(x1))
len(x1)

<class 'list'>


4

In [ ]:
x=np.array([2.0,4.6,9.3,1.2])#la lista se convirtió en una matriz o array
#siempre va el alias de la libreria seguido de un punto
print(type(x))
len(x)

<class 'numpy.ndarray'>


4

#Accediento a elementos de una matriz de dos dimensiones y 3 dimensiones

**Unidimensional**

In [ ]:
numeros = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
print(numeros)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
print(numeros[:])

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
print(numeros[3:8])#La posición 8 no lo toma en cuenta

[13 14 15 16 17]


**Matriz de dos dimensiones**

In [ ]:
A=[[1,2,3],[7,8,9],[13,14,15],[19,20,21]]#tiene como posiciones 0,1,2,3
#  ...0.......1........2..........3......

In [ ]:
A[0][1]

2

In [ ]:
A[1]

[7, 8, 9]

In [ ]:
A[1:3]

[[7, 8, 9], [13, 14, 15]]

In [ ]:
A[1:2]

[[7, 8, 9]]

**Matriz de tres dimensiones**, dentro de los parentesis van las matrices de dos dimensiones

In [ ]:
notas_3d=[
    [[1,2,3],[4,5,6]],
     [[7,8,9],[10,11,12]]]#Es una matriz de 2x2x3..tiene 2 filas, 2 columnas y 3 de profundidad

In [ ]:
len(notas_3d)

2

In [ ]:
notas_3d[0]

[[1, 2, 3], [4, 5, 6]]

In [ ]:
notas_3d[1]

[[7, 8, 9], [10, 11, 12]]

In [ ]:
notas_3d[0][0]

[1, 2, 3]

In [ ]:
notas_3d[1][1]

[10, 11, 12]

In [ ]:
notas_3d[0][0][2]

3

In [ ]:
notas_3d[1][1][2]

12

#Creación de arrays
Creación de array especiales de ceros, unos, vacío, unidimensionalmente

In [ ]:
ceros=np.zeros(5)
print(ceros)

[0. 0. 0. 0. 0.]


In [ ]:
unos=np.ones(5)
print(unos)

[1. 1. 1. 1. 1.]


In [ ]:
vacio1=np.empty(4)#sale cualquier cosa
print(vacio1)

[4.99394629e-310 0.00000000e+000 6.92288616e-310 6.92288618e-310]


**Creando una matriz de dos dimensiones**

In [ ]:
x=np.array([[2,4.6],[9.3,1.2]])
print(x)

[[2.  4.6]
 [9.3 1.2]]


In [ ]:
x[0]

array([2. , 4.6])

In [ ]:
x[0][1]

4.6

In [ ]:
len(x)

2

In [ ]:
x.shape

(2, 2)

In [ ]:
print(type(x))

<class 'numpy.ndarray'>


In [ ]:
z=np.array([[2,4.6],[9.3,1.2],[1,0.6]])

In [ ]:
z[1:,0]#extra las filas [9.3,1.2] [1,0.6] pero, la columna cero osea 9.3,1

array([9.3, 1. ])

In [ ]:
z[1:,-1]#la última columna es -1, la penúltima columna es -2, extrae como fila [9.3,1.2],[1,0.6] pero con la columna -1 osea 1.2 y 0.6

array([1.2, 0.6])

In [ ]:
z[2:,:]

array([[1. , 0.6]])

In [ ]:
z[1:,:]

array([[9.3, 1.2],
       [1. , 0.6]])

In [ ]:
z[1:,-2]#saca la penúltima columna.

array([9.3, 1. ])

In [ ]:
z[2,1]

0.6

In [ ]:
print("z =\n",z)

z =
 [[2.  4.6]
 [9.3 1.2]
 [1.  0.6]]


In [ ]:
print("Segmento de z = \n",z[1:,:])

Segmento de z =
 [[9.3 1.2]
 [1.  0.6]]


In [ ]:
z[0:2,0]#el primer elemento 0:2 ve las filas(no toma en cuenta el 2), 0 las columnas.

array([2. , 9.3])

##**Creación de array especiales de ceros, unos, vacío, unidimensionalmente**

In [ ]:
ceros1=np.zeros((5,4))#de tamaño 5(filas)x4(columnas)
print(ceros1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
zeros=np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
unos1=np.ones((5,4))
print(unos1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
unos2=np.ones((5,1))#unidimensional vertical
print(unos2)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [ ]:
unos2.shape

(5, 1)

In [ ]:
unos3=np.ones((1,5))#unidimensional horizontal
print(unos3)

[[1. 1. 1. 1. 1.]]


In [ ]:
vacio1=np.empty((2,3))#imprime basura
print(vacio1)

[[2.  4.6 9.3]
 [1.2 1.  0.6]]


**Creando matriz de 3 dimensiones**

In [ ]:
y=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
#Es un cubo con cara(elementos)...1,4 (posicion 0_lado superior) y 7,10(posicion 1_lado inferior)
#el 2,3....5,6......8,9.....11,12....son la profundidad del cubo
#El parentesis en azul es 0 y 1
#El parentesis en amarillo es 0 y 1
#La posción de los elementos en amarillo es 0,1,2

In [ ]:
print(type(y))

<class 'numpy.ndarray'>


In [ ]:
print(y)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
y[1][0][1]

8

In [ ]:
y[1][1][2]

12

In [ ]:
len(y)

2

In [ ]:
y[1,1,:]
#para el primer elemento ver la matriz como un todo las sub matrices seran 0,1,2 segun cuantas hayan y seran la filas
#para el segundo elemento ver lo que esta dentro de la sun  matriz y cada lista sera 0,1,2 según hayan
#para el tercer elemento la profundidad (o ver como si fuera las columnas de una matriz bidimensional)

array([10, 11, 12])

In [ ]:
print(y)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


[0:,:,1:] ver como si fuera un cubo

In [ ]:
y[0:,:,1:]#el primer elemento 0: ve filas, el segundo : columnas, y el tercero 1: profundidad

array([[[ 2,  3],
        [ 5,  6]],

       [[ 8,  9],
        [11, 12]]])

In [ ]:
y[0:,1,1:]
#0:, considera todas las filas 0 y 1, la primera matriz [1,2,3 y 4,5,6] es fila 0 y la segunda matriz [7,8,9 y 4,5,6] es 1
#1, considera la columna 1, los elementos de la columna 1 son [4,5,6] y [10,11,12]
#1:, ver la profundidad 0(1,4 y 7,10),1(2,5 y 8,11),2 (3,6 y 9,12)

array([[ 5,  6],
       [11, 12]])

In [ ]:
y[0:,:,0]

array([[ 1,  4],
       [ 7, 10]])

In [ ]:
print(y.shape)

(2, 2, 3)


**Creación de array randomicos**

In [ ]:
alea=np.random.rand(2,3)#crea una matriz de 2 por 3 de tipo float
print(alea)

[[0.96390938 0.48841425 0.81123783]
 [0.06407815 0.25056784 0.3863668 ]]


In [ ]:
age=np.random.randint(8,10)#Genera un número aleatorio entre 8 y 10, sin considerar el 10
print(age)

9


In [ ]:
array=np.random.randint(5,10,size=(2,3))#genera una matriz de 2 por 3, pero de entero
print(array)

[[8 7 9]
 [8 6 8]]


In [ ]:
array=np.random.randint(1,10,size=(3,3))
print(array)

[[8 7 6]
 [2 5 2]
 [9 4 9]]


#Operaciones matemáticas con arrays, lo hace elemento por elemento y para ejectuarse la operación deben tener ambos arreglos osea el mismo tamaño.

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 3, 1,3])

In [ ]:
 print("Suma= \n",a+b)

Suma= 
 [2 5 4 7]


In [ ]:
print("Multiplicación= \n",a*b)

Multiplicación= 
 [ 1  6  3 12]


In [ ]:
print("Resta= \n",a-b)

Resta= 
 [ 0 -1  2  1]


In [ ]:
print("Division= \n",a/b)

Division= 
 [1.         0.66666667 3.         1.33333333]


In [ ]:
print("Division= \n",a%b)#residuo

Division= 
 [0 2 0 1]


In [ ]:
print("Potencia= \n",a**b)

Potencia= 
 [ 1  8  3 64]


In [ ]:
print("Raiz cuadrada de la matriz a= \n",np.sqrt(a))#llamamos a numpy y luego llamamos a la funcion sqrt

Raiz cuadrada de la matriz a= 
 [1.         1.41421356 1.73205081 2.        ]


**Operaciones de matrices bidimensionales, las operaciones se hacen punto a punto**

In [ ]:
c=np.array([[1,0],[-1,2],[1,3]])
c.shape

(3, 2)

In [ ]:
d=np.array([[-3,3],[2,0],[7,16]])
d.shape

(3, 2)

In [ ]:
e=d.reshape(2,3)
e.shape

(2, 3)

In [ ]:
print("Suma: \n",c+d)

Suma: 
 [[-2  3]
 [ 1  2]
 [ 8 19]]


In [ ]:
print("Multiplicación: \n",c*d)

Multiplicación: 
 [[-3  0]
 [-2  0]
 [ 7 48]]


In [ ]:
print("Resta: \n",c-d)

Resta: 
 [[  4  -3]
 [ -3   2]
 [ -6 -13]]


**Multiplicación de matrices con el operador @**
la primera matriz es de tamaño mxn, la segunda matriz pxq
para efectuar la multiplicación se debe cumplir n=p

In [ ]:
f=c@e
print(f)

[[-3  3  2]
 [ 3 11 30]
 [-3 24 50]]


#Propiedades de las matrices

##**Transpuesta de una matriz**

In [ ]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(A.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
a_t=np.transpose(A)
print(a_t)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
print(np.transpose(A))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


##**Función reshape**

In [ ]:
d = np.array([1, 2, 3, 4, 5, 8])

In [ ]:
e = d.reshape(2, 3)#realiza un arreglo con filas 2 y 3 columnas
print(e)

[[1 2 3]
 [4 5 8]]


In [ ]:
f = d.reshape(3,2)#realiza un arreglo con 3 filas y 2 columnas
print(f)

[[1 2]
 [3 4]
 [5 8]]


##**Indexación booleana, permite seleccionar elementos basado en condiciones**

In [ ]:
 w= np.array([x for x in range(1,11)])
 print(w)
mask=np.array([True,False,True,False,True,False,True,False,True,False])
f=w[mask]
print(f)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [ ]:
mask1=w<=7  #La mascara puede usarse como condición
g=w[mask1]
print(g)

[1 2 3 4 5 6 7]


#**EJERCICIOS**

**1.- Crear el vector con valores aleatorios de tamaño 30**

In [25]:
a=np.array(np.random.randint(0,50,24))# El números aleatorios van de 0 a 50 y el tercer elemento indica la cantidad de números aleatorios.
print(a)

[ 2  8  0  5 38 47 15 35 33 38  5 44 31 15  6 39 45  1 19 25 13 10  8 28]


In [8]:
a1=np.random.randint(50,size=24)#Serán size=24 números aleatorios de 0 a 50
print(a1)

[25 38 16 48 40 29 21  4 22 28 36 33 14  2  4 28 48 22  7 27 17 41 26 48]


In [21]:
a2=[x for x in np.array(np.random.randint(0,10,5))]
print(a2)

[6, 3, 1, 3, 0]


**2.- Invertir el vector creada anteriormente**

In [18]:
print(a[::-1])

[16 10 18 46  6 28  7 13  4 34 28 16 36 49 46 35 22 46 11  5 26 42  2  8]


In [19]:
print(a1[::-1])

[48 26 41 17 27  7 22 48 28  4  2 14 33 36 28 22  4 21 29 40 48 16 38 25]


In [22]:
print(a2[::-1])

[0, 3, 1, 3, 6]


In [24]:
b=a.reshape(24,1)
print(b)

[[ 8]
 [ 2]
 [42]
 [26]
 [ 5]
 [11]
 [46]
 [22]
 [35]
 [46]
 [49]
 [36]
 [16]
 [28]
 [34]
 [ 4]
 [13]
 [ 7]
 [28]
 [ 6]
 [46]
 [18]
 [10]
 [16]]


3. Crear una matriz de 4x4 con valores aleatorios

In [27]:
s=np.array(np.random.randint(100, size=(4,4)))
print(s)

[[31 87  8 81]
 [65 60 28 15]
 [92 25 68 96]
 [ 9 37 76  8]]


In [28]:
type(s)

numpy.ndarray

In [29]:
x =np.array(np.random.randint(100, size=(5,5)))
type(x)

numpy.ndarray

In [ ]:
print(x)

[[32 76 93 69 79]
 [ 3 87 22 38 77]
 [44 66  4 51  0]
 [74 33 29 79 45]
 [ 9 59 87 15 24]]


In [33]:
g=[x for x in np.random.randint(10, size=(3,3))]
print(g)

[array([0, 4, 7]), array([3, 6, 3]), array([4, 8, 2])]


4. Crear una matriz de tamaño 6x6 en donde
- La diagonal tenga 1 (matriz A)
- La antidiagonal tenga 1 (matriz B)

In [34]:
A=np.identity(6)
print(A)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [35]:
A1=np.eye(6)
print(A1)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [36]:
matriz=np.random.randint(10, size=(6,6))
for i in range(6):
  print(matriz[i])

[4 4 4 6 1 3]
[3 0 1 1 9 0]
[5 1 5 8 5 1]
[6 6 9 6 0 7]
[2 5 3 5 9 8]
[8 5 9 7 1 7]


Matriz antidiagonal

In [40]:
mdiag=np.fliplr(np.identity(6))
print(mdiag)

[[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]


In [44]:
iden=np.identity(6)
m1diag=iden[::-1]
print(m1diag)

[[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]


5.- Crear dos matrices con valores aleatorios e indicar despues si tienen valores iguales(posiciones)

In [45]:
m1=np.random.randint(10,size=(6,6))
m2=np.random.randint(10,size=(6,6))

In [46]:
mask= (m1==m2)
print(mask)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]
 [False False False False False False]
 [False False False  True False False]]


In [47]:
print(np.equal(m1,m2))

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]
 [False False False False False False]
 [False False False  True False False]]


In [48]:
print(m1)
print(m2)

[[1 8 4 2 3 7]
 [2 6 3 7 6 0]
 [6 9 2 7 6 3]
 [0 8 3 0 3 7]
 [1 0 8 2 2 0]
 [6 6 2 9 2 1]]
[[2 9 8 8 8 6]
 [1 7 2 3 2 3]
 [1 2 5 6 9 0]
 [3 5 4 0 5 5]
 [6 8 3 9 6 9]
 [5 9 9 9 1 2]]


In [53]:
print(np.where(m1==m2))

(array([3, 5]), array([3, 3]))


6.- Crear una matriz con valores aleatorios y hacer una funcion que sume los valores de cada fila

In [61]:
z =np.array(np.random.randint(100, size=(3,3)))
print(z)

[[74 46 24]
 [88 88 93]
 [ 6 94 69]]


In [58]:
z[2,2]

90

In [65]:
for i in range(len(z)):
  suma=0
  for j in range (len(z[0])):
    suma=suma+z[i,j]
  print(suma)


144
269
169


In [86]:
#imprimiendo posiciones
for i in range(len(z)):
  list=[]
  #suma=0
  for j in range (len(z[0])):
    cordenada=i,j
    list.append(cordenada)
  print(list)


[(0, 0), (0, 1), (0, 2)]
[(1, 0), (1, 1), (1, 2)]
[(2, 0), (2, 1), (2, 2)]


In [67]:
print(np.sum(z,1))#con 1 suma filas y con cero suma columnas

[144 269 169]


In [70]:
print(np.sum(z,0))

[168 228 186]


In [71]:
print(np.sum(z))

582


7.- Usando la matriz anterior sumar los valores que están en la diagonal

In [87]:
suma=0
for i in range(len(z)):

  for j in range (len(z[0])):
    if i==j:
      suma=suma+z[i,j]
print(suma)

231


In [88]:
np.sum(np.diagonal(z))

231

8.-Con la matriz creada en el ejercicio 6, modificar los primeros valores que estan en cada fila y reemplazar con 10

In [89]:
z[0:,0]=10
print(z)

[[10 46 24]
 [10 88 93]
 [10 94 69]]


9.-

In [90]:
np.max(z,0)

array([10, 94, 93])

In [ ]:
M=[[2,2,1,3,2],[3,4,2,2,1],[1,3,4,3,4],[2,3,2,4,2],[1,2,3,4,1]]

In [ ]:
M=np.array(M)
print(M)

[[2 2 1 3 2]
 [3 4 2 2 1]
 [1 3 4 3 4]
 [2 3 2 4 2]
 [1 2 3 4 1]]


In [ ]:
M[0][3]

3

3.Cantidad de veces que aparecen los numeros

4.Cree una función LISTAR(matriz) la cual imprima los valores de la matriz (sin repetirse),
(con la imagen de la matriz anterior se tiene:)

5.Indicar la suma de los valores de la matriz en donde la suma de sus posiciones (x+y) estén
en el intervalo de 6 a 13

In [ ]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [ ]:
fils = 255
cols = 255
matrix = np.zeros([fils, cols, 3], dtype=np.uint8)
for i in range(fils):
 for j in range(cols):
  matrix[i][j] = [0, 0, 255]

plt.imshow(matrix)

In [ ]:
fils = 255
cols = 255
matrix = np.zeros([fils, cols, 3], dtype=np.uint8)
for i in range(fils):
 for j in range(cols):
  matrix[i][j] = [0, 0, i]

plt.imshow(matrix)

In [ ]:
fils = 255
cols = 255
matrix = np.zeros([fils, cols, 3], dtype=np.uint8)
for i in range(fils):
 for j in range(cols):
  matrix[i][j] = [i, 0, j]

plt.imshow(matrix)

In [ ]:
fils = 255
cols = 255
matrix = np.zeros([fils, cols, 3], dtype=np.uint8)
for i in range(fils):
 for j in range(cols):
  matrix[i][j] = [i, j, 0]
plt.imshow(matrix)

In [ ]:
fils = 26
cols = 26
matrix = np.zeros([fils, cols, 3], dtype=np.uint8)
for i in range(fils):
  for j in range(cols):
    if i%5 == 0 or j%5 == 0:
      matrix[i][j] = [255, 255, 255]
    else:
      matrix[i][j] = [0, 0, 0]
plt.imshow(matrix)

In [ ]:
matrix = np.zeros([100, 300, 3], dtype=np.uint8)
matrix[:,:100] = [255, 0, 0] # Rojo
matrix[:,100:200] = [255, 255, 255] # Blanco
matrix[:,200:] = [255, 0, 0] # Rojo
plt.imshow(matrix)